name: daily main

on:
    schedule:
      - cron: "30 6 * * 1-5"
    workflow_dispatch:

env:
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  CHAT_ID: ${{ secrets.CHAT_ID }}
  CHAT_ID_DAILY: ${{ secrets.CHAT_ID }}
  TOKEN: ${{ secrets.TOKEN }}
  HEADLESS: ${{ secrets.HEADLESS }}
  QASE_REPORT: 1
  QASE_PROJECT_CODE: INT
  QASE_RUN_COMPLETE: true
  QASE_TESTOPS_API_TOKEN: ${{ secrets.QASE_TESTOPS_API_TOKEN }}

jobs:
  build-php:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: tests
        run: pytest tests/test_hello_2
        continue-on-error: true