name: 3 tests

on:
  schedule:
    - cron: "12 3 * * *"
  workflow_dispatch:

env:
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  CHAT_ID: ${{ secrets.CHAT_ID }}
  HEADLESS: ${{ secrets.HEADLESS }}
  TOKEN: ${{ secrets.TOKEN }}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run autotests
    steps:
      - name: Download repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4.1.4

      - name: tests
        # if: "github.event.inputs.deployment_target == 'all'"
        run: pytest tests/test_tags/prod tests/test_forms/prod tests/test_review/prod tests/test_search  --alluredir=allure-results
        continue-on-error: true